name: btelnyy
main: btelnyy.plugin.main
version: 1.3.1
api-version: 1.18
commands:
   suicide:
      description: Kills you instantly.
      usage: /suicide
      permission: btelnyy.command.suicide
   dc:
      description: Kicks you from the server.
      usage: /dc
      permission: btelnyy.command.dc
   vtp:
      description: Starts a vote to punish a player.
      usage: /vtp <player> <ban/kick>
      permission: btelnyy.vote.start
   vote:
      description: Vote on the current vote
      usage: /vote <yes/no>
      permission: btelnyy.vote
   rules:
      description: Print server rules.
      usage: /rules
      permission: btelnyy.command.rules
   voterestart:
      description: Start a vote to restart the server.
      usage: /voterestart
      permission: btelnyy.vote.srvrestart
   ping:
      description: Get your ping to the server.
      usage: /ping
      permission: btelnyy.command.ping
