name: btelnyy-core
main: me.btelnyy.core.Main
version: ${project.version}
api-version: 1.18
commands:
   suicide:
      description: Kills you instantly.
      usage: /suicide
      permission: btelnyy.command.suicide
   dc:
      description: Kicks you from the server.
      usage: /dc
      permission: btelnyy.command.dc
   vtp:
      description: Starts a vote to punish a player.
      usage: /vtp <player> <ban/kick>
      permission: btelnyy.vote.start
   vote:
      description: Vote on the current vote
      usage: /vote <yes/no>
      permission: btelnyy.vote
   rules:
      description: Print server rules.
      usage: /rules
      permission: btelnyy.command.rules
   voterestart:
      description: Start a vote to restart the server.
      usage: /voterestart
      permission: btelnyy.vote.srvrestart
   ping:
      description: Get your ping to the server.
      usage: /ping
      permission: btelnyy.command.ping
   pvp:
      description: Toggle global pvp
      usage: /pvp
      permission: btelnyy.command.pvp
   hardcore:
      description: Toggle hardcore mode (temporary)
      usage: /hardcore
      permission: btelnyy.command.hardcore
   revive:
      description: Revive a dead player (if they died to the plugins hardcore mode, only has effect if GHOST is the option)
      usage: /revive <player>
      permission: btelnyy.command.revive
   reviveall:
      description: Revive all dead players
      usage: /reviveall
      permission: btelnyy.command.reviveall
   whereami:
      description: Get your position
      usage: /whereami
      permission: btelnyy.command.whereami
   breload:
      description: Reloads btelnyy-core's config
      usage: /breload
      permission: btelnyy.command.reloadcore